### PR TITLE
[Feature] bootstrap init command

### PR DESCRIPTION
**Pull request by mirzahilmi**
[+] generate cmd/api/main.go based on choosed framework
[+] generate Dockerfile
[+] generate .dockerignore
[+] generate Makefile

### CODE REVIEW

**Comment by NupalHariz** [comment]
I tried to generate app with wrong flags. ex:
```
bccli init todo -framework laravel
```
This command generate will generate go.mod, go.sum, and cmd/api/main.go but the main.go will be empty and there's a message `Error: templte: pattern matches no files: "tmpl/unknown_main.tmpl"`.
I think we should check the flags first before start creating the stucture of project

**Comment by mirzahilmi** [comment]
will fix

**Comment by mirzahilmi** [comment]
@NupalHariz fixed, you can check & test it
image

**Comment by NupalHariz** [comment]
> @NupalHariz fixed, you can check & test it image

This change looks good to me. I’ve already tested it, and it works really well.
I have a question about the `echo_main.tmpl`: should we remove it, or should we add a case for Echo in `framework.go`?
Screenshot 2024-09-22 at 18 24 02

**Comment by mirzahilmi** [comment]
itll be added later on, just keep it for now

**Comment by NupalHariz** [comment]
> itll be added later on, just keep it for now

Okay thanks for the information

**Pull request merged**
